
# This config file is for use with the `build_data` and `check_data` functions,
# which are helpers for implementations of Open SDG. This file allows easy use
# of those functions without altering Python code.

# Languages
# ---------
# This tells sdg-build to perform "translated builds" for each of the specified
# languages. Each build is in its own subfolder - one for each language.
languages:
  - en
  
# Destination directory
# ---------------------
# This identifies a directory to hold the "built" files. The default is '_site'.
site_dir: _site

# Schema file
# -----------
# This identifies a file containing the schema (possible fields) for metadata.
# Currently this needs to be a prose.io config, and defaults to '_prose.yml'.
schema_file: metadata_schema.yml

# Source directory
# ----------------
# This identifies the directory that holds the 'data' and 'meta' folders.
# The default, '', points to the root of this repository.
src_dir: ''

# Inputs
# ------
# The allows control over the inputs of data and metadata. This can be omitted
# if you are using the standard Open SDG approach of CSV data and YAML metadata.
# But if you would like to use non-standard inputs (such as SDMX) then you can
# use this as needed.
#
# Each item must have a "class" which corresponds to classes in the sdg/inputs
# folder. Further, each item can have any/all of the parameters that class uses.
# The defaults below show what is used when this is omitted.
inputs:
  #- class: InputSdmxMl_Multiple
  #  path_pattern: data/*.xml
  #  dsd: 'LocalRegistry.xml'
  - class: InputSdmxMl_Structure
    source: https://zw.sdmx.afdb.org/ns-ws/rest/data/ZW1,DF_ZW_SDG,1.0/A............../ALL/?detail=full&dimensionAtObservation=TIME_PERIOD
    dsd: https://zw.sdmx.afdb.org/ns-ws/rest/datastructure/ZW1/SDG/1.1/?detail=Full&references=Descendants
    dimension_map:
      REF_AREA|ZW: ''
    drop_dimensions:
      - FREQ
      - REPORTING_TYPE
      - NATURE
      - TIME_PERIOD
    drop_singleton_dimensions: false
    import_series_attributes: true
    import_observation_attributes: true
    import_codes: true
    indicator_id_map:
     EN_MAT_DOMCMPT: 8-4-2
     EN_MAT_DOMCMPC: 8-4-2
     EN_MAT_DOMCMPG: 8-4-2
     VC_VOV_DCMN: 16-b-1
     SG_INT_MBRDEV: 10-6-1
     EN_NAA_PLAN_DV: 13-2-1
     ER_WLD_TRPOACH: 15-7-1
     VC_DSR_MISS: 1-5-1
     VC_DSR_MORT: 1-5-1
     VC_DSR_DAFF: 1-5-1
     VC_DSR_MISS: 11-5-1
     VC_DSR_MORT: 11-5-1
     VC_DSR_DAFF: 11-5-1
     SG_DSR_LEGREG: 1-5-3
     SG_DSR_LEGREG: 11-b-1
     SG_DSR_LEGREG: 13-1-2
     SG_DSR_SILS: 1-5-4
     SG_DSR_SILS: 11-b-2
     SG_DSR_SILS: 13-1-3
     SE_GCEDESD_NEP: 4-7-1
     SE_GCEDESD_CUR: 4-7-1
     SE_GCEDESD_TED: 4-7-1
     SE_GCEDESD_NEP: 12-8-1
     SE_GCEDESD_CUR: 12-8-1
     SE_GCEDESD_TED: 12-8-1
     SE_GCEDESD_NEP: 13-3-1
     SE_GCEDESD_CUR: 13-3-1
     SE_GCEDESD_TED: 13-3-1
    request_params: 
      headers: 
        User-Agent: Open-SDG-Build-1 
  - class: InputWordMeta
    path_pattern: meta/*-*.docm
  - class: InputYamlMeta
    path_pattern: indicator-config/*-*.yml
    git: false
  - class: InputYamlMeta
    # This describes the meta files, relative to the "src_dir" indicated above.
    path_pattern: meta/*-*.yml
    git: false
  - class: InputSdmxMeta
    meta_suffix: __GLOBAL

# Translations
# ------------
# The allows control over the imported translations. This can be omitted if you
# are happy with the defaults. But if you are using custom translation repos
# or non-standard inputs (such as SDMX) then you can use this as needed.
#
# Each item must have a "class" which corresponds to classes in the sdg-build
# project. Further, each item can have any/all of the parameters that class uses.
# The defaults below show what is used when this is omitted.
translations:
  # This pulls in translations from a Git repository.
  - class: TranslationInputSdgTranslations
    source: https://github.com/open-sdg/sdg-translations.git
    tag: 2.4.0
  # This pulls in translations from a local 'translations' folder.
  - class: TranslationInputYaml
    source: translations
  #- class: TranslationInputSdmx
  #  source: 'LocalRegistry.xml'
  - class: TranslationInputSdmx
    source: https://zw.sdmx.afdb.org/ns-ws/rest/datastructure/ZW1/SDG/1.1/?detail=Full&references=Descendants
    request_params:
      headers:
        User-Agent: Open-SDG-Build-1

# Reporting status extra fields
# -----------------------------
# This allows the build to generate stats for reporting status by additional
# fields, beyond the default "status by goal" report.
reporting_status_extra_fields: []

# Map layers
# ----------
# This allows the build to generate one or more GeoJSON files to be used by
# Open SDG maps. The parameters available correspond to the OutputGeoJson class.
# See sdg/outputs/OutputGeoJson.py for more information. Uncomment the map_layers
# below and adjust if you would like to use the Open SDG mapping functionality.
# Note that the GeoJSON files can either be remote (as in the example below) or
# local, relative to the src_dir specified above.
map_layers:
  - geojson_file: geojsons/National_By_District.geojson
    name_property: ADM1_EN
    id_property: ADM1_PCODE
    output_subfolder: regions
    filename_prefix: indicator_

# Documentation settings
# ----------------------
# This controls the automatic documentation that is created for your build.
#
# This is the logo at the top of the automated documentation pages.
docs_branding: SDG data build documentation
# This displays at the top of the automated documentation homepage.
docs_intro: This is a list of examples of endpoints and output that are
  available on this service. Click each of the links below for more information
  on the available output.
# This can be uncommented and updated so allow links to your indicator pages.
# The URL here should have [id] instead of the indicator ID.
#docs_indicator_url: https://my-github-org/my-site-repository/[id]
# This can be uncommented to show translation columns in the disaggregation report.
docs_translate_disaggregations: true
# This can be uncommented to show additional columns in the disaggregation report.
# This is mainly intended to show units of measurement and series, which are not
# normally considered "disaggregation".
# docs_extra_disaggregations: ['Units', 'Series']

# This controls the metadata report which is part of the automatic documentation.
# More info can be found at https://open-sdg.readthedocs.io/en/latest/data-configuration/#docs_metadata_fields
docs_metadata_fields:
    - key: reporting_status
      label: Reporting status
    - key: SDG_CUSTODIAN_AGENCIES__GLOBAL
      label: UN custodian agency
    - key: data_non_statistical
      label: Non-statistical
    - key: data_show_map
      label: Show map
    - key: national_geographical_coverage
      label: Geographical coverage
    - key: computation_units
      label: Units
    - key: graph_type
      label: Graph type

indicator_options:
  non_disaggregation_columns:
    - Year
    - Units
    - Series
    - Value
    - GeoCode
    - Observation status
    - Unit multiplier
    - Unit measure
    - UNIT_MEASURE
    - SERIES
    - COMMENT_TS
    - DATA_LAST_UPDATE
    - TIME_DETAIL
  series_column: SERIES
  unit_column: UNIT_MEASURE
  observation_attributes:
    - COMMENT_OBS
    - SOURCE_DETAIL
